export interface CountryHierarchyMapping {
  countryCode: string; // ISO 2-letter
  countryName: string;
  continent: string;
  level0: string; // Earth
  level1: string; // Continent
  level2: string; // Subregion
  level3: string; // Country (ADM0)
  level4: string; // ADM1 (State / Province)
  level5: string; // ADM2 (District / County)
  level6: string; // ADM3 (Taluk / Sub-district)
  level7: string; // ADM4 (City / Town / Village)
  level8: string; // Neighborhood / Ward
  level9: string; // Postal Code
  level10: string; // Street / Road
  level11: string; // Building / POI
  level12: string; // Business / Hospital / School
}

export const WORLD_HIERARCHY_MAPPINGS: CountryHierarchyMapping[] = [
  // --- ASIAN COUNTRIES ---
  {
    countryCode: 'IN',
    countryName: 'India',
    continent: 'Asia',
    level0: 'Earth',
    level1: 'Asia',
    level2: 'Southern Asia',
    level3: 'Country (India)',
    level4: 'State / Union Territory (e.g. Tamil Nadu, Maharashtra)',
    level5: 'District (e.g. Chennai, Pune)',
    level6: 'Taluk / Tehsil / Sub-division (e.g. Ambattur, Haveli)',
    level7: 'City / Town / Village / Panchayat (e.g. Chennai, Kanchipuram)',
    level8: 'Neighborhood / Ward (e.g. Anna Nagar, Ward 85)',
    level9: 'Postal Index Number PIN (e.g. 600040)',
    level10: 'Street & Road (e.g. Mount Road, 2nd Avenue)',
    level11: 'Building & Point of Interest (e.g. Apollo Hospital)',
    level12: 'Business / Hospital / School / Storefront',
  },
  {
    countryCode: 'CN',
    countryName: 'China',
    continent: 'Asia',
    level0: 'Earth',
    level1: 'Asia',
    level2: 'Eastern Asia',
    level3: 'Country (China)',
    level4: 'Province Sheng / Autonomous Region (e.g. Guangdong, Zhejiang)',
    level5: 'Prefecture Dishi / Sub-prefectural City (e.g. Guangzhou)',
    level6: 'County Xian / District Qu (e.g. Tianhe District)',
    level7: 'Township Xiang / Sub-district Jiedao (e.g. Linhe Jiedao)',
    level8: 'Village Cun / Residential Community Shequ',
    level9: 'Postal Code (e.g. 510000)',
    level10: 'Street & Road Lu / Jie (e.g. Tianhe Road)',
    level11: 'Building & Point of Interest (e.g. Canton Tower)',
    level12: 'Business / Hospital / School / Storefront',
  },
  {
    countryCode: 'JP',
    countryName: 'Japan',
    continent: 'Asia',
    level0: 'Earth',
    level1: 'Asia',
    level2: 'Eastern Asia',
    level3: 'Country (Japan)',
    level4: 'Prefecture Todōfuken (e.g. Tokyo, Osaka)',
    level5: 'Subprefecture / District Gun (e.g. Nishitama)',
    level6: 'Municipality City/Ward/Town/Village (e.g. Shinjuku Ward)',
    level7: 'District Machi / Aza (e.g. Kabukichō)',
    level8: 'Chōme / Neighborhood (e.g. Kabukichō 1-chōme)',
    level9: 'Postal Code Yūbinbangō (e.g. 160-0021)',
    level10: 'Street & Block Number (Banchi / Gō)',
    level11: 'Building & Point of Interest (e.g. Shinjuku Station)',
    level12: 'Business / Hospital / School / Storefront',
  },
  {
    countryCode: 'ID',
    countryName: 'Indonesia',
    continent: 'Asia',
    level0: 'Earth',
    level1: 'Asia',
    level2: 'South-Eastern Asia',
    level3: 'Country (Indonesia)',
    level4: 'Province Provinsi (e.g. West Java, Bali)',
    level5: 'Regency Kabupaten / City Kota (e.g. Bandung)',
    level6: 'District Kecamatan (e.g. Coblong)',
    level7: 'Sub-district Kelurahan / Village Desa (e.g. Dago)',
    level8: 'Community Unit RW / RT',
    level9: 'Postal Code Kode Pos (e.g. 40135)',
    level10: 'Street Jalan (e.g. Jalan Dago)',
    level11: 'Building & Point of Interest (e.g. ITB Campus)',
    level12: 'Business / Hospital / School / Storefront',
  },
  {
    countryCode: 'PK',
    countryName: 'Pakistan',
    continent: 'Asia',
    level0: 'Earth',
    level1: 'Asia',
    level2: 'Southern Asia',
    level3: 'Country (Pakistan)',
    level4: 'Province / Territory (e.g. Punjab, Sindh)',
    level5: 'Division / District (e.g. Lahore District)',
    level6: 'Tehsil / Sub-division (e.g. Lahore City Tehsil)',
    level7: 'Union Council / City / Village',
    level8: 'Neighborhood / Mohallah / Sector (e.g. Gulberg)',
    level9: 'Postal Code (e.g. 54000)',
    level10: 'Street & Road (e.g. Mall Road)',
    level11: 'Building & Point of Interest (e.g. Badshahi Mosque)',
    level12: 'Business / Hospital / School / Storefront',
  },
  {
    countryCode: 'BD',
    countryName: 'Bangladesh',
    continent: 'Asia',
    level0: 'Earth',
    level1: 'Asia',
    level2: 'Southern Asia',
    level3: 'Country (Bangladesh)',
    level4: 'Division Bibhag (e.g. Dhaka, Chittagong)',
    level5: 'District Zila (e.g. Dhaka District)',
    level6: 'Sub-district Upazila / Thana (e.g. Dhanmondi Thana)',
    level7: 'Union / Municipality Pourashava / Village',
    level8: 'Mahalla / Village Ward',
    level9: 'Postal Code (e.g. 1205)',
    level10: 'Street & Road (e.g. Mirpur Road)',
    level11: 'Building & Point of Interest (e.g. Dhaka University)',
    level12: 'Business / Hospital / School / Storefront',
  },
  {
    countryCode: 'PH',
    countryName: 'Philippines',
    continent: 'Asia',
    level0: 'Earth',
    level1: 'Asia',
    level2: 'South-Eastern Asia',
    level3: 'Country (Philippines)',
    level4: 'Region / Autonomous Region (e.g. NCR, CALABARZON)',
    level5: 'Province (e.g. Laguna, Cebu)',
    level6: 'City / Municipality (e.g. Quezon City, Santa Rosa)',
    level7: 'Barangay (e.g. Barangay Central)',
    level8: 'Sitio / Purok / Neighborhood',
    level9: 'ZIP Code (e.g. 1100)',
    level10: 'Street & Avenue (e.g. EDSA, Quezon Avenue)',
    level11: 'Building & Point of Interest (e.g. SM Mall of Asia)',
    level12: 'Business / Hospital / School / Storefront',
  },
  {
    countryCode: 'VN',
    countryName: 'Vietnam',
    continent: 'Asia',
    level0: 'Earth',
    level1: 'Asia',
    level2: 'South-Eastern Asia',
    level3: 'Country (Vietnam)',
    level4: 'Province Tỉnh / Municipality Thành phố (e.g. Hanoi, HCMC)',
    level5: 'District Quận / Huyện / Town Thị xã (e.g. District 1)',
    level6: 'Ward Phường / Commune Xã (e.g. Bến Nghé Ward)',
    level7: 'Hamlet Thôn / Quarter Tổ dân phố',
    level8: 'Neighborhood / Sub-quarter',
    level9: 'Postal Code (e.g. 700000)',
    level10: 'Street Đường (e.g. Nguyễn Huệ Street)',
    level11: 'Building & Point of Interest (e.g. Bitexco Tower)',
    level12: 'Business / Hospital / School / Storefront',
  },
  {
    countryCode: 'KR',
    countryName: 'South Korea',
    continent: 'Asia',
    level0: 'Earth',
    level1: 'Asia',
    level2: 'Eastern Asia',
    level3: 'Country (South Korea)',
    level4: 'Special City / Province Do (e.g. Seoul, Gyeonggi-do)',
    level5: 'City Si / County Gun / District Gu (e.g. Gangnam-gu)',
    level6: 'Town Eup / Township Myeon / Neighborhood Dong (e.g. Yeoksam-dong)',
    level7: 'Village Ri / Sub-neighborhood',
    level8: 'Neighborhood Block / Tong',
    level9: 'Postal Code (e.g. 06164)',
    level10: 'Street Doro (e.g. Teheran-ro)',
    level11: 'Building & Point of Interest (e.g. COEX Center)',
    level12: 'Business / Hospital / School / Storefront',
  },
  {
    countryCode: 'SA',
    countryName: 'Saudi Arabia',
    continent: 'Asia',
    level0: 'Earth',
    level1: 'Asia',
    level2: 'Western Asia',
    level3: 'Country (Saudi Arabia)',
    level4: 'Province Mintaqah (e.g. Riyadh Region, Makkah)',
    level5: 'Governorate Muhafazah (e.g. Jeddah Governorate)',
    level6: 'Sub-governorate Marakiz',
    level7: 'City Madinah / Village Qaryah (e.g. Jeddah)',
    level8: 'District / Neighborhood Hayy (e.g. Al-Hamra)',
    level9: 'Postal Code (e.g. 21577)',
    level10: 'Street Shari (e.g. King Road)',
    level11: 'Building & Point of Interest (e.g. Kingdom Centre)',
    level12: 'Business / Hospital / School / Storefront',
  },
  {
    countryCode: 'TR',
    countryName: 'Turkey',
    continent: 'Asia / Europe',
    level0: 'Earth',
    level1: 'Asia',
    level2: 'Western Asia',
    level3: 'Country (Turkey)',
    level4: 'Province İl (e.g. Istanbul, Ankara)',
    level5: 'District İlçe (e.g. Kadıköy, Çankaya)',
    level6: 'Town Bucak / Sub-district',
    level7: 'Quarter Mahalle / Village Köy (e.g. Caferağa Mahalle)',
    level8: 'Neighborhood / Zone',
    level9: 'Posta Kodu (e.g. 34710)',
    level10: 'Street Sokak / Cadde (e.g. Bağdat Caddesi)',
    level11: 'Building & Point of Interest (e.g. Hagia Sophia)',
    level12: 'Business / Hospital / School / Storefront',
  },
  {
    countryCode: 'TH',
    countryName: 'Thailand',
    continent: 'Asia',
    level0: 'Earth',
    level1: 'Asia',
    level2: 'South-Eastern Asia',
    level3: 'Country (Thailand)',
    level4: 'Province Changwat / Special Area (e.g. Bangkok, Chiang Mai)',
    level5: 'District Amphoe / Khet (e.g. Pathum Wan)',
    level6: 'Sub-district Tambon / Khwaeng (e.g. Lumphini)',
    level7: 'Village Muban / Urban Community',
    level8: 'Neighborhood / Soi Sub-street',
    level9: 'Postal Code (e.g. 10330)',
    level10: 'Street Thanon (e.g. Sukhumvit Road)',
    level11: 'Building & Point of Interest (e.g. Siam Paragon)',
    level12: 'Business / Hospital / School / Storefront',
  },

  // --- NON-ASIAN REPRESENTATIVE COUNTRIES ---
  {
    countryCode: 'US',
    countryName: 'United States',
    continent: 'North America',
    level0: 'Earth',
    level1: 'North America',
    level2: 'Northern America',
    level3: 'Country (United States)',
    level4: 'State (e.g. California, Texas)',
    level5: 'County (e.g. Los Angeles County)',
    level6: 'Township / Municipality',
    level7: 'City / Town (e.g. Los Angeles)',
    level8: 'Neighborhood (e.g. Hollywood)',
    level9: 'ZIP Code (e.g. 90028)',
    level10: 'Street & Road (e.g. Sunset Boulevard)',
    level11: 'Building & POI',
    level12: 'Business / Hospital / School',
  },
  {
    countryCode: 'DE',
    countryName: 'Germany',
    continent: 'Europe',
    level0: 'Earth',
    level1: 'Europe',
    level2: 'Western Europe',
    level3: 'Country (Germany)',
    level4: 'Bundesland (e.g. Bayern)',
    level5: 'Regierungsbezirk / Landkreis (e.g. Oberbayern)',
    level6: 'Gemeindeverband',
    level7: 'Gemeinde / Stadt (e.g. München)',
    level8: 'Stadtteil (e.g. Schwabing)',
    level9: 'PLZ (e.g. 80331)',
    level10: 'Straße',
    level11: 'Gebäude & POI',
    level12: 'Geschäft / Schule',
  },
  {
    countryCode: 'GB',
    countryName: 'United Kingdom',
    continent: 'Europe',
    level0: 'Earth',
    level1: 'Europe',
    level2: 'Northern Europe',
    level3: 'Country (United Kingdom)',
    level4: 'Constituent Country (e.g. England)',
    level5: 'County / Unitary Authority',
    level6: 'District / Borough',
    level7: 'City / Town (e.g. London)',
    level8: 'Locality / Neighborhood',
    level9: 'Postcode (e.g. SW1A 1AA)',
    level10: 'Street & Road',
    level11: 'Building & POI',
    level12: 'Business / School',
  }
];

export function getHierarchyMapping(countryCode: string): CountryHierarchyMapping {
  const upper = countryCode.toUpperCase();
  const found = WORLD_HIERARCHY_MAPPINGS.find((m) => m.countryCode === upper);
  if (found) return found;

  // Default fallback mapping for all other countries
  return {
    countryCode: upper,
    countryName: countryCode,
    continent: 'Worldwide',
    level0: 'Earth',
    level1: 'Continent',
    level2: 'Subregion',
    level3: `Country (${upper})`,
    level4: 'State / Province / Region (ADM1)',
    level5: 'District / County / Department (ADM2)',
    level6: 'Taluk / Tehsil / Municipality (ADM3)',
    level7: 'City / Town / Village (ADM4)',
    level8: 'Neighborhood / Ward',
    level9: 'Postal Code',
    level10: 'Street & Road',
    level11: 'Building & Point of Interest (POI)',
    level12: 'Business / Hospital / School / Storefront',
  };
}
